### PR TITLE
w9b4: Fix missing "nav-link" for Navbar links

### LINKED ISSUE #866: Menu is broken in 5.0.0
All menu links doesn't have `nav-link` CSS class, so the styling is broken
The issue is caused by this 1bda15b7411186cff1b08eb568aa8b539684a0f6 commit

### PR DESCRIPTION
**Pull request by mweirauch**
This PR is based upon @solomax work in #867 with button-groups fixed.

The CSP fix for the samples application is a separate commit, so that the main fix could potentially be backported to w8b4.

Things look like this now:

image

Fixes #866

### CODE REVIEW

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/navbar/NavbarDropDownButton.java [hunk 1]
```diff
@@ -66,23 +61,7 @@ protected final void addButtonBehavior(final ButtonBehavior buttonBehavior) {
...
     protected WebMarkupContainer newButton(String markupId, IModel<String> labelModel, final IModel<IconType> iconTypeModel) {
         WebMarkupContainer button = super.newButton(markupId, labelModel, iconTypeModel);
-        button.add(new CssClassNameRemover("btn"));
-        button.add(new CssClassNameAppender(Buttons.Type.Menu.cssClassName()));
+        button.add(new CssClassNameAppender(Buttons.Type.NavLink.cssClassName()));
         return button;
     }
-
-    @Override
-    protected ButtonList newButtonList(String markupId) {
```
Comment (solomax) [inline bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/navbar/NavbarDropDownButton.java:75]: I see design issue here: every class which will override `newButtonList` will have `dropdown-item` CSS class dropped :(

I had in plans to fix it as well ...

Comment (mweirauch) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/navbar/NavbarDropDownButton.java:75]: Ah I see, that's why you moved this to `ButtonList::configureLink`. Nevertheless the design issue was there before and after realising this code is "useless" in the sense `Buttons.Type.Menu` is not providing anything meaningful anymore, I opted to drop it entirely.

Perhaps you can come up with a better design after the main issues are fixed?

Comment (solomax) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/bootstrap/navbar/NavbarDropDownButton.java:75]: sure, it is not blocker here
I wrote it to not forget :) (sort of "notes to myself" :)) )

**Comment by solomax** [comment]
just was able to test everything locally (sorry for delay :( )
Everything seems to be great :)
@martin-g can you check and merge this PR?

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you, @mweirauch & @solomax !
I've backported it to w-8.x-b-4.x

**Comment by martin-g** [comment]
5.0.1 has been released!

**Comment by solomax** [comment]
Thanks for the release @martin-g !
