### PR TITLE
fixes #951: configurable BootstrapBundle is introduced

### LINKED ISSUE #951: Bootstrap-confirmation is broken because of Popper
Latest `M7` release contains broken `confirmation`
After some digging I find-out this is because we have `popper` as additional dependency

The modern way is to drop it and use `bootstrap.bundle` instead
(see for ex. here https://stackoverflow.com/a/72336371)

Shall I proceed with such change?
Or Maybe it would be better (for whatever reason) have this behavior configurable?

@martin-g, @ursjoss WDYT? :)

### PR DESCRIPTION
**Pull request by solomax**
I would better drop all `popper.js` related code and keep `bootstrap.bundle` only :)

### CODE REVIEW

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapBundleJavaScriptReference.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
+package de.agilecoders.wicket.core.markup.html.references;
+
+import de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference;
+
+/**
+ * represents the bootstrap js library
+ *
+ * @author miha
```
Comment (martin-g) [inline bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapBundleJavaScriptReference.java]: I am pretty sure `miha` does not care about this anymore :-)

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapJavaScriptReference.java [hunk 2]
```diff
@@ -45,7 +44,6 @@ private BootstrapJavaScriptReference() {
     @Override
     public List<HeaderItem> getDependencies() {
         return Dependencies.combine(super.getDependencies(),
-                                    JavaScriptHeaderItem.forReference(Application.get().getJavaScriptLibrarySettings().getJQueryReference()),
```
Comment (martin-g) [inline bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapJavaScriptReference.java:48]: Why ?

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java [hunk 3]
```diff
@@ -53,6 +57,7 @@ public BootstrapSettings() {
         this.updateSecurityManager = true;
         this.autoAppendResources = true;
         this.useCdnResources = false;
+        this.useBundle = false;
```
Comment (martin-g) [inline bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: Maybe we should switch to `true` as default. Otherwise your reported [issue](https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/951) would be still valid, no ?

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapJavaScriptReference.java (hunk 2 above)
Comment (solomax) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapJavaScriptReference.java:48]: As I understand from here: https://getbootstrap.com/docs/5.2/getting-started/introduction/
Bootstrap doesn't depends on jQuery anymore ...

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java (hunk 3 above)
Comment (solomax) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: Well,
popper version need to be fixed, via (additional) commit

IMO it worth to switch to bundle-only mode, this would make things simpler :)

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapJavaScriptReference.java (hunk 2 above)
Comment (martin-g) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapJavaScriptReference.java:48]: Good point!

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java (hunk 3 above)
Comment (martin-g) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: I agree with bundle-only setup!

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapBundleJavaScriptReference.java (hunk 1 above)
Comment (solomax) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/markup/html/references/BootstrapBundleJavaScriptReference.java]: Addressed :)

File: bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java (hunk 3 above)
Comment (solomax) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: Done :)

`MaterialDesignTheme` and `ItaliaTheme` still requires Popper (seems to)
but they are for bootstrap4 only :(

Shall we keep or drop it?

Comment (martin-g) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: I'd suggest to just remove these lines:
* https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/7010be70febdbe34d8adad3629b501056f767a8b/bootstrap-themes/src/main/java/de/agilecoders/wicket/themes/markup/html/italia/ItaliaTheme.java#L54
* https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/7010be70febdbe34d8adad3629b501056f767a8b/bootstrap-themes/src/main/java/de/agilecoders/wicket/themes/markup/html/material_design/MaterialDesignTheme.java#L32

Comment (solomax) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: done
Also dropped useless dependency :)

Comment (martin-g) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: https://github.com/l0rdn1kk0n/wicket-bootstrap/blob/7010be70febdbe34d8adad3629b501056f767a8b/bootstrap-themes/src/main/java/de/agilecoders/wicket/themes/markup/html/material_design/MaterialDesignTheme.java#L32
Do we still need this ?

Comment (solomax) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: this one is dropped already
will lead to compilation error otherwise :)

Comment (martin-g) [reply bootstrap-core/src/main/java/de/agilecoders/wicket/core/settings/BootstrapSettings.java]: Right! I am looking at the target branch ... 🤦🏻

**Review by martin-g — APPROVED** [review]

**Comment by solomax** [comment]
I'd love to get release/new-snapshot as soon this one be merged :)

**Comment by martin-g** [comment]
6.0.0-M8-SNAPSHOT has been uploaded to Sonatype!

**Comment by solomax** [comment]
Thanks a million! :)
